version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-mcs25-file_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: file_db
    ports:
      - 5435:5432
  minio:
    image: minio/minio:latest
    container_name: minio-mcs25
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"