spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5435/auth_db
    username: root
    password: root
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
server:
  port: 8082
