spring:
  application:
    name: file-service
  datasource:
    url: jdbc:postgresql://localhost:5435/file_db
    username: root
    password: root
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

minio:
  login: minioadmin
  password: minioadmin
  url: http://localhost:9000
  bucket: first-bucket